import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "components/card";
import Spline from "@splinetool/react-spline";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="flex flex-col h-full lg:flex-row justify-center">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="grid place-content-top font-rubik-MonoOne text-cream w-fit h-fit backdrop-blur-sm  p-6 rounded-[10px]
      bg-cocoa-dark/50"
      >
        <section className=" mb-16 text-xl">
          <p>
            HI! I&apos;m Johnny! I&apos;m a UCR Computer Science<br></br>
            Student with a passion for Design and Code.
          </p>
        </section>
        <div className="mb-16 text-xl flex flex-col">
          <h2 className="mb-3">Current Projects</h2>
          <div className="flex flex-col sm:flex-row  sm:space-x-4">
            <Card
              name="UCR Map Project"
              text="React Native map application designed for University of California, Riverside students."
              language="Javascript"
              langaugeColor="#d9c334"
              href="https://github.com/Drabblesaur/CS178AProject"
            />
            <Card
              name="Task Scheduler"
              text="Terminal-Based C++ Task Manager created for CS100."
              language="C++"
              langaugeColor="#044F88"
              href="https://github.com/Drabblesaur/CS100_Task_Scheduler"
            />
          </div>
        </div>
      </div>
    </div>
  );
}
